services:
  - type: web
    name: nethawk-backend
    env: docker
    plan: free
    dockerfilePath: ./nethawk-backend/Dockerfile
    envVars:
      - key: FRONTEND_URL
        value: https://nethawk-dsh.vercel.app  # For Vercel
        
